<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="TestTasksSuite" duration-ms="527432" started-at="2018-12-12T00:50:04Z" finished-at="2018-12-12T00:58:51Z">
    <groups>
    </groups>
    <test name="tests.TestTaskTwo" duration-ms="40590" started-at="2018-12-12T00:50:04Z" finished-at="2018-12-12T00:50:45Z">
      <class name="tests.TestTaskTwo">
        <test-method status="PASS" signature="beforeTestClass()[pri:0, instance:tests.TestTaskTwo@1593948d]" name="beforeTestClass" is-config="true" duration-ms="4688" started-at="2018-12-12T00:50:04Z" finished-at="2018-12-12T00:50:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestClass -->
        <test-method status="PASS" signature="testTopSearchIsFunctional()[pri:0, instance:tests.TestTaskTwo@1593948d]" name="testTopSearchIsFunctional" duration-ms="35712" started-at="2018-12-12T00:50:09Z" description="test that searched element is finally found on any iteration." finished-at="2018-12-12T00:50:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTopSearchIsFunctional -->
        <test-method status="PASS" signature="afterTestClass()[pri:0, instance:tests.TestTaskTwo@1593948d]" name="afterTestClass" is-config="true" duration-ms="177" started-at="2018-12-12T00:50:44Z" finished-at="2018-12-12T00:50:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestClass -->
      </class> <!-- tests.TestTaskTwo -->
    </test> <!-- tests.TestTaskTwo -->
    <test name="tests.TestTaskOne" duration-ms="486638" started-at="2018-12-12T00:50:45Z" finished-at="2018-12-12T00:58:51Z">
      <class name="tests.TestTaskOne">
        <test-method status="PASS" signature="beforeTestClass()[pri:0, instance:tests.TestTaskOne@47c62251]" name="beforeTestClass" is-config="true" duration-ms="5412" started-at="2018-12-12T00:50:45Z" finished-at="2018-12-12T00:50:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestClass -->
        <test-method status="FAIL" signature="testFilteredElementsHaveCorrectTag()[pri:0, instance:tests.TestTaskOne@47c62251]" name="testFilteredElementsHaveCorrectTag" duration-ms="480901" started-at="2018-12-12T00:50:50Z" description="Test if the first element has a label &quot;new&quot; and all &quot;new&quot; items on the page appear next to each other, while all items without such label are further down." finished-at="2018-12-12T00:58:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Was found element with tag new expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Was found element with tag new expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at tests.TestTaskOne.testFilteredElementsHaveCorrectTag(TestTaskOne.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFilteredElementsHaveCorrectTag -->
        <test-method status="PASS" signature="afterTestClass()[pri:0, instance:tests.TestTaskOne@47c62251]" name="afterTestClass" is-config="true" duration-ms="323" started-at="2018-12-12T00:58:51Z" finished-at="2018-12-12T00:58:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestClass -->
      </class> <!-- tests.TestTaskOne -->
    </test> <!-- tests.TestTaskOne -->
  </suite> <!-- TestTasksSuite -->
</testng-results>
